version: '3.1'

services:
  postgres:
    container_name: event-finder-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: events
    ports:
      - 5432:5432